import type { LocaleBundle } from './types';

/**
 * Message lookup and number formatting for the frame.
 *
 * Text never comes from the server as prose: the server sends translation
 * keys and numeric arguments, and this module resolves them. That is what
 * allows a Persian challenge to be generated by a Go process that has no font
 * and no text shaper, and it means adding a language is a matter of adding
 * one JSON file.
 */
export class Translator {
  readonly tag: string;
  readonly dir: 'ltr' | 'rtl';
  readonly rtl: boolean;
  private readonly messages: Record<string, string>;
  private readonly digits: string;

  constructor(bundle: LocaleBundle) {
    this.tag = bundle.tag;
    this.dir = bundle.meta.dir === 'rtl' ? 'rtl' : 'ltr';
    this.rtl = this.dir === 'rtl';
    this.messages = bundle.messages || {};
    this.digits = bundle.meta.digits || 'latn';
  }

  /**
   * Looks up a message and substitutes {placeholders}. Numeric values are
   * rendered with the locale's digits, so a Persian visitor sees ۳ rather
   * than 3 without any call site having to think about it.
   */
  t(key: string, params?: Record<string, string | number>): string {
    const template = this.messages[key];
    if (template === undefined) {
      // Showing the key makes a missing translation obvious in testing
      // rather than silently rendering an empty label.
      return key;
    }
    if (!params) return template;
    return template.replace(/\{(\w+)\}/g, (whole, name: string) => {
      const value = params[name];
      if (value === undefined) return whole;
      return typeof value === 'number' ? this.num(value) : value;
    });
  }

  /** Formats a number using the locale's numeral system. */
  num(value: number): string {
    const plain = String(value);
    if (this.digits !== 'arabext') return plain;
    // U+06F0 is the first Extended Arabic-Indic (Persian) digit. The Arabic
    // digits at U+0660 look different in Persian typography, so the distinct
    // Persian range is the correct one here.
    return plain.replace(/[0-9]/g, (d) => String.fromCharCode(0x06f0 + Number(d)));
  }

  /** Joins a list the way the locale expects, for "click star, moon and sun". */
  list(items: string[]): string {
    if (items.length <= 1) return items[0] ?? '';
    // Persian uses the Arabic comma and "و" as the final conjunction.
    const separator = this.rtl ? '، ' : ', ';
    const last = items[items.length - 1];
    const head = items.slice(0, -1).join(separator);
    return this.rtl ? `${head} و ${last}` : `${head} & ${last}`;
  }

  /** The localised name of a shape identifier such as "crescent". */
  shape(id: string): string {
    return this.t(`shape.${id}`);
  }

  /**
   * Physical direction of "forward" for this locale. The slider track and the
   * progress fill mirror in RTL so that dragging "forwards" means dragging
   * towards the reading direction.
   */
  get forward(): 1 | -1 {
    return this.rtl ? -1 : 1;
  }
}
